### ISSUE TITLE
Error while downloading the models

### ISSUE THREAD

**Issue by gadorneles** [butia-bots/butia_speech#19]
While downloading the models for the first time after using the package I encountered the following error:

```
Traceback (most recent call last):
File "/root/butia_ws/src/butia_speech/nodes/speech_synthesizer.py", line 51, in <module>
with open(os.path.join(PACK_DIR, "include/model/total_count/model.pkl"),'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/butia_ws/src/butia_speech/include/model/total_count/model.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/butia_ws/src/butia_speech/nodes/speech_synthesizer.py", line 71, in <module>
with open(os.path.join(PACK_DIR, "include/model/total_count/model.pkl"), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/butia_ws/src/butia_speech/include/model/total_count/model.pkl'
```
It was simply resolved by creating the directory butia_speech/include/model/total_count, but it might be best to think of a permanent solution.

**Comment by PedroCorcaque** [comment]
A solução proposta em https://github.com/butia-bots/butia_speech/commit/e93bb9c33cfc0cbc7021fe9c9412b2ccfc9367e5 é criar o caminho antes de acessar, até mesmo do bloco try/except. 

**Solução precisa ser testada.**

**Comment by PedroCorcaque** [comment]
PR https://github.com/butia-bots/butia_speech/commit/824d57c0a676e8b79b02cf044bb3654b290c9b25 resolve o problema.
